# Generated by Django 5.1 on 2024-08-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.BigIntegerField(default=1, verbose_name='Student Number'),
            preserve_default=False,
        ),
    ]
