# Generated by Django 5.1 on 2024-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Student Number'),
        ),
    ]
